apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes: # Define volume
        - name: shared-log
          persistentVolumeClaim:
            claimName: mypvc-claim
      containers:
        - name: ping-pong
          image: aaartyoms/ping-pong:0.0.8v
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
