apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ping-pong-volume-claim
  namespace: small-apps
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
