apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-ping-pong-volume
  namespace: small-apps
  labels:
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/data
