apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: small-apps
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - port: 4444
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: small-apps
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
