apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylog
  namespace: small-apps
spec:
  selector:
    matchLabels:
      app: mylog
  template:
    metadata:
      labels:
        app: mylog
    spec:
      volumes: # Define volume
        - name: shared-log
          persistentVolumeClaim:
            claimName: mypvc-claim
        - name: config
          configMap:
            name: log-config-map
      containers:
        - name: mylog
          image: aaartyoms/logger-reader:0.0.29v
          imagePullPolicy: IfNotPresent
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
            - name: config
              mountPath: /usr/src/app/config
        - name: log-writer
          image: aaartyoms/logger-writer:0.0.29v
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
