apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-inserter-ns
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-inserter-ns
              image: alpine:3.17
              env:
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_DB
              command: [
                  "sh",
                  "-c",
                  "apk add --no-cache postgresql-client && \
                  export PGPASSWORD=$POSTGRES_PASSWORD && \
                  psql -h postgres-service -U $POSTGRES_USER -d $POSTGRES_DB -c \"INSERT INTO todo (text) VALUES ('https://en.wikipedia.org/wiki/Special:Random');\"",
                ]
          restartPolicy: OnFailure
