apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project
spec:
  selector:
    matchLabels:
      app: todo-project
  template:
    metadata:
      labels:
        app: todo-project
    spec:
      containers:
      - name: todo-backend
        image: aaartyoms/todo-project-backend
