apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project
spec:
  selector:
    matchLabels:
      app: todo-project
  template:
    metadata:
      labels:
        app: todo-project
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/BACKEND-IMAGE
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
              path: /probe
              port: 3000
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 5
            httpGet:
              path: /probe
              port: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NATS_URL
              value: nats://my-nats:4222
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
        - name: todo-frontend
          image: PROJECT/FRONTEND-IMAGE
        - name: todo-broadcaster
          image: PROJECT/BROADCASTER-IMAGE
          env:
            - name: NATS_URL
              value: nats://my-nats:4222
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: webhook-secret
                  key: WEBHOOK_URL
