apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project
spec:
  selector:
    matchLabels:
      app: todo-project
  template:
    metadata:
      labels:
        app: todo-project
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/BACKEND-IMAGE
          resources:
            requests:
              memory: "180Mi"
            limits:
              cpu: "150m"
              memory: "256Mi"
          env:
            - name: PORT
              value: "3000"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
        - name: todo-frontend
          image: PROJECT/FRONTEND-IMAGE
          resources:
            requests:
              memory: "180Mi"
            limits:
              cpu: "150m"
              memory: "256Mi"
