apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project
spec:
  selector:
    matchLabels:
      app: todo-project
  template:
    metadata:
      labels:
        app: todo-project
    spec:
      containers:
        - name: todo-backend
          image: aaartyoms/todo-project-backend:0.0.3v
          env:
            - name: PORT
              value: "3000"
        - name: todo-frontend
          image: aaartyoms/todo-project-frontend:0.0.1v
