apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project
  namespace: todo-ns
spec:
  selector:
    matchLabels:
      app: todo-project
  template:
    metadata:
      labels:
        app: todo-project
    spec:
      containers:
        - name: todo-backend
          image: aaartyoms/todo-project-backend:0.0.11v
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PORT
              value: "3000"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
        - name: todo-frontend
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          image: aaartyoms/todo-project-frontend:0.0.7v
