apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cpushredder-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpushredder-dep
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: Resource
      resources:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
