apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-project-pvc-claim
spec:
  storageClassName: todo-project-persistent-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
