apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylog
spec:
  selector:
    matchLabels:
      app: mylog
  template:
    metadata:
      labels:
        app: mylog
    spec:
      containers:
      - name: mylog
        image: aaartyoms/logger-img
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
