name: Release application

on:
  delete:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  BACKEND_IMAGE: todo-project-backend
  FRONTEND_IMAGE: todo-project-frontend
  BRANCH: ${{ github.ref_name }}
  AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}

jobs:
  build-publish-deploy:
    name: Delete namespace of the feature branch
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: gcloud info

      - name: "Configure GCR"
        run: gcloud --quiet auth configure-docker

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: "Delete feature"
        run: |-
          kubectl get namespace
          kubectl delete namespace ${GITHUB_REF#refs/heads/}
